### ISSUE TITLE
Lint failing on an unknown file

### ISSUE THREAD

**Issue by satazor** [ipfs/testing#121]
## Which Project is this about?

https://github.com/ipfs/js.ipfs.io

## Provide a link to a example run where it went wrong

https://ci.ipfs.team/blue/organizations/jenkins/IPFS%2Fjs.ipfs.io/detail/production/29/pipeline

## Which platform did the issue happen on?

--

-------

The latest master commit has passed the pipeline, as you can see here: https://ci.ipfs.team/blue/organizations/jenkins/IPFS%2Fjs.ipfs.io/detail/master/154/pipeline

I then proceeded to push the changes to `production` but it's always failing on the lint step, on a file called `site/build-html-styles.css`. This file doesn't exist on the repo. Note that the lint command runs before any build step. Note that the commit that previously has passed is the same as the one from the master branch.

I'm struggling on understanding the issue. Help? :|

**Comment by satazor** [comment]
Tried to do a dummy commit to see if I get around it but it's now happening on master too :/

https://ci.ipfs.team/blue/organizations/jenkins/IPFS%2Fjs.ipfs.io/detail/master/156/pipeline

**Comment by satazor** [comment]
I might be wrong but it seems that the `/site` folder contains some left overs of some previous failed build somehow .

`docker cp 3f964c167e1be91fd47cff7dabf5a552afdda8565cd87b3146c74695d0998d2d:/site/public/ ./site`

If that is confirmed to be the case, can we perhaps use different folders to prevent this from happening again?

**Comment by VictorBjelkholm** [comment]
Solved in https://github.com/ipfs/jenkins-libs/commit/cf2cf1460f7e34d666d014cef41b7f692e6fddd0#diff-f3940bdfa00670170b326e572ff3920d

**Comment by satazor** [comment]
I’ve replayed a build and it’s still failing: https://ci.ipfs.team/blue/organizations/jenkins/IPFS%2Fjs.ipfs.io/detail/production/33/pipeline

**Comment by VictorBjelkholm** [comment]
@satazor yeah, the UI of ci.ipfs.team/blue is bad. Replaying a build will copy the parameters to the new build (including which git commits to use, including the pipeline git commit), which means it'll basically run exactly the same thing.

However, in the old UI, there is a "rebuild" option, that will rerun the same job but take new parameters. This will get you the new pipeline code that solves this issue. Here is the new build I started by doing a rebuild: https://ci.ipfs.team/blue/organizations/jenkins/IPFS%2Fjs.ipfs.io/detail/production/34/pipeline

Made a quick recording showing where you can find the rebuild: https://ipfs.io/ipfs/Qmc3cw2K52QDT6b47BE76fgmgnuQNPWjAb8vhqaJdSTscQ/out.ogv

**Comment by satazor** [comment]
Thank you very much, seems to be working now!
